spring:
  application:
    name: BikeTasks
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false